- name: variables from play level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Praveen"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}" # Two double flowers for ansible variables


