- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{DevOps}}, Trainer is {{Trainer}}, Duration is {{Duration}}"